[project]
name = "oci-cost-tool"
version = "0.1.0"
description = "Initial version of OCI cost tool"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "oci>=2.164.2",
    "tabulate>=0.9.0",
]
